- name: Install docker
  hosts: myhosts
  become: true
  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Check Docker info
      shell: docker info
      register: docker_info_output
      ignore_errors: yes

    - name: Print Docker info output
      debug:
        var: docker_info_output.stdout_lines

    - name: Enable required container features
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: 'cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'
        line: 'cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'
        insertafter: EOF

    - name: Reboot the system
      reboot:
        msg: "Rebooting to apply kernel changes."