k3s_cluster:
  children:
    server:
      hosts:
        10.42.42.100:
    agent:
      hosts:
        10.42.42.101:
        10.42.42.102:
  vars:
    ansible_user: tom.mclean
    k3s_version: v1.31.3+k3s1
    token: Bxmehsbo7iLP9ZSPz4BuYu02iTBDaehaXd9oTi66Ey5hG3m5DYR2IjqDVn87GZPmFLuXwFke4Lae7XskrG5rZQ==
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"